# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(gradle_path: "../gradlew", task: "test")
  end

  desc "Submit a new Alpha build to Google Play"
  lane :alpha do
    upload_to_play_store(track: 'alpha', apk: 'build/outputs/apk/production/release/app-production-release.apk')
  end

  desc "Promote the Alpha build to Beta on Google Play"
  lane :beta do
    supply(
           track: "alpha",
           track_promote_to: "beta",
           skip_upload_apk: true,
           skip_upload_metadata: true,
           skip_upload_images: true,
           skip_upload_screenshots: true,
          )
  end

  desc "Promote the Beta build to production on Google Play"
  lane :production do
    supply(
           track: "beta",
           track_promote_to: "production",
           skip_upload_apk: true,
           skip_upload_metadata: true,
           skip_upload_images: true,
           skip_upload_screenshots: true,
          )
  end
end
