# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(gradle_path: "../gradlew", task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    upload_to_play_store(track: 'alpha', apk: 'build/outputs/apk/app-zproduction-debug.apk')
    UI.message("Promoted version code (alpha): #{google_play_track_version_codes(track: "alpha")}")
    # UI.message("Promoted version code (production): #{google_play_track_version_codes}")
    # UI.message("Promoted version code (beta): #{google_play_track_version_codes(track: "beta")}")
  end

  #desc "Deploy a new version to the Google Play"
  #lane :production do
    #gradle(gradle_path: "../gradlew", task: "clean assembleRelease")
    #upload_to_play_store
  #end
end
